version: '3.8'

services:
  backrest:
    image: backrest/backrest:latest
    container_name: backrest
    restart: unless-stopped
    environment:
      - RESTIC_REPOSITORY=/mnt/restic-backups/optiplex/server
      - RESTIC_PASSWORD=supersecret
      - TZ=America/New_York
    volumes:
      # NFS mount for backups
      - /mnt/restic-backups:/mnt/restic-backups
      # Example: include system config dirs you want to back up
      - /etc:/data/etc:ro
      - /home:/data/home:ro
    ports:
      - "8081:8080"
    labels:
      - "com.portainer.description=Backrest Web UI for server-level backups"
      - "com.portainer.vlan=lan"
      - "com.portainer.owner=Thomas"

  stackback:
    image: ghcr.io/stackback/stackback:latest
    container_name: stackback
    restart: unless-stopped
    environment:
      - RESTIC_REPOSITORY=/mnt/restic-backups/optiplex/docker
      - RESTIC_PASSWORD=supersecret
      - TZ=America/New_York
    volumes:
      # NFS mount for backups
      - /mnt/restic-backups:/mnt/restic-backups
      # Needed so Stack-Back can inspect Docker volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    labels:
      - "com.portainer.description=Stack-Back for Docker volume backups"
      - "com.portainer.vlan=lan"
      - "com.portainer.owner=Thomas"

volumes:
  # Optional: if you want to mount NFS directly via Docker instead of host mount
  restic_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.200.3,nfsvers=4,rw
      device: :/volume1/docker_backups/OptiPlex_Docker
